{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mbhealth.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mbhealth.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
  {{- with (include "mbhealth.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # Application secret key
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  {{- if .Values.secrets.encryptionKey }}
  # Encryption key for sensitive data
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  {{- end }}
---
{{- if or .Values.secrets.apiKeys.openai .Values.secrets.apiKeys.anthropic .Values.secrets.apiKeys.googleAI .Values.secrets.apiKeys.openrouter }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mbhealth.apiKeysSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mbhealth.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-keys
  {{- with (include "mbhealth.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.secrets.apiKeys.openai }}
  OPENAI_API_KEY: {{ .Values.secrets.apiKeys.openai | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKeys.anthropic }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.apiKeys.anthropic | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKeys.googleAI }}
  GOOGLE_AI_API_KEY: {{ .Values.secrets.apiKeys.googleAI | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKeys.openrouter }}
  OPENROUTER_API_KEY: {{ .Values.secrets.apiKeys.openrouter | quote }}
  {{- end }}
{{- end }}
{{- end }}