{{- if .Values.serviceAccount.create -}}
# Backend Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mbhealth.backend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mbhealth.backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
# Worker Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mbhealth.worker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mbhealth.worker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
# Frontend Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mbhealth.frontend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mbhealth.frontend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
# Migration Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mbhealth.migration.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mbhealth.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}