apiVersion: batch/v1
kind: Job
metadata:
  name: mbhealth-db-migration
  namespace: mbhealth
  labels:
    app.kubernetes.io/name: mbhealth-migration
    app.kubernetes.io/component: migration
    app.kubernetes.io/part-of: mbhealth
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mbhealth-migration
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: OnFailure
      serviceAccountName: mbhealth-migration
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        # Wait for database to be ready
        - name: wait-for-db
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER; do
                echo "Waiting for database..."
                sleep 5
              done
              echo "Database is ready!"
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mbhealth-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: mbhealth-config
                  key: DATABASE_PORT
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mbhealth-secret
                  key: DATABASE_USER
      containers:
        - name: migration
          image: mbhealth/backend:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Running database migrations..."
              alembic upgrade head
              echo "Migrations completed successfully!"
          env:
            - name: DATABASE_URL
              value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mbhealth-secret
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mbhealth-secret
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mbhealth-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: mbhealth-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: mbhealth-config
                  key: DATABASE_NAME
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
# ServiceAccount for migrations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mbhealth-migration
  namespace: mbhealth
  labels:
    app.kubernetes.io/name: mbhealth-migration
    app.kubernetes.io/component: migration