{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mbhealth.fullname" . }}-frontend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mbhealth.frontend.labels" . | nindent 4 }}
  {{- with (include "mbhealth.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "mbhealth.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mbhealth.frontend.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mbhealth.frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.securityContext | nindent 8 }}
      containers:
        - name: frontend
          image: {{ include "mbhealth.image" (dict "registry" .Values.global.imageRegistry "repository" .Values.frontend.image.repository "tag" (.Values.frontend.image.tag | default .Chart.AppVersion)) }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            # Frontend runtime configuration
            - name: VITE_API_URL
              value: {{ .Values.frontend.config.apiUrl | quote }}
            - name: VITE_WS_URL
              value: {{ .Values.frontend.config.wsUrl | quote }}
            - name: VITE_APP_NAME
              value: {{ .Values.frontend.config.appName | quote }}
            - name: VITE_LOG_LEVEL
              value: {{ .Values.frontend.config.logLevel | quote }}
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: frontend-config
              mountPath: /docker-entrypoint.d/40-inject-env.sh
              subPath: nginx-env-config.sh
              readOnly: true
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: frontend-config
          configMap:
            name: {{ include "mbhealth.frontendConfigMapName" . }}
            defaultMode: 0755
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}