apiVersion: v2
name: mbhealth
description: A comprehensive health data tracking application with AI analysis
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/matburt/mbhealth
sources:
  - https://github.com/matburt/mbhealth
keywords:
  - health
  - tracking
  - ai
  - analysis
  - medical
maintainers:
  - name: MBHealth Team
    email: support@mbhealth.example.com

dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    tags:
      - database
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    tags:
      - cache

annotations:
  category: Healthcare
  licenses: MIT